# Generated by Django 4.0.4 on 2022-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
