# Generated by Django 4.0.4 on 2022-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_due_to_task_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.CharField(max_length=30),
        ),
    ]
