# Generated by Django 4.0.4 on 2022-09-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
    ]
