# Generated by Django 4.0.4 on 2022-09-05 00:36

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_priority_remove_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=api.models.IntegerRangeField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=api.models.IntegerRangeField(default=1),
        ),
    ]
