# Generated by Django 4.0.4 on 2022-09-05 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_priority_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
