# Generated by Django 4.0.4 on 2022-09-05 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
